/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto2edd;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedReader;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.filechooser.FileSystemView;
import static proyecto2edd.ManejoArchivo.lecturaArchivo;

/**
 *
 * @author ernes
 */
public class Interfaz extends javax.swing.JFrame {

    public static Lista listaArticulos = new Lista();
    public static Articulo articulo = new Articulo();
    public static HashTable hashTitulo = new HashTable(1000);
    public static HashTable hashAutores = new HashTable(1000);
    public static HashTable hashPalabras = new HashTable(1000);

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BotonAgregar = new javax.swing.JButton();
        BotonBPAutor = new javax.swing.JButton();
        BotonBPPC = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ArticulosPorTitulo = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BotonAgregar.setText("Agregar archivo");
        BotonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAgregarActionPerformed(evt);
            }
        });
        jPanel1.add(BotonAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, -1, -1));

        BotonBPAutor.setText("ver Articulos por Autor");
        BotonBPAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonBPAutorActionPerformed(evt);
            }
        });
        jPanel1.add(BotonBPAutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, -1, -1));

        BotonBPPC.setText("ver Articulos por Palabras Claves");
        BotonBPPC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonBPPCActionPerformed(evt);
            }
        });
        jPanel1.add(BotonBPPC, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 240, -1, -1));

        jLabel1.setText("Bienvenido a la libreria de articulos");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 240, 30));

        jLabel2.setText("Para agregar un articulo a la base de datos ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        jLabel3.setText("Para ver los articulos almacenados puedes hacerlo por:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        ArticulosPorTitulo.setText("Analizar articulo");
        ArticulosPorTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ArticulosPorTituloActionPerformed(evt);
            }
        });
        jPanel1.add(ArticulosPorTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 130, -1, -1));

        jLabel4.setText("Para analizar un articulo de la base de datos");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        jLabel5.setText("Creado por Ernesto Lugo y David Mizrahi");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, -1, -1));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/53a57d5b1adffe00c12a7ed37e7990aa.jpg"))); // NOI18N
        jPanel1.add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 360));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 557, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAgregarActionPerformed
        JFileChooser jfc = new JFileChooser(FileSystemView.getFileSystemView().getHomeDirectory());
        jfc.setDialogTitle("Selecciona un archivo de texto (.txt)");
        jfc.setAcceptAllFileFilterUsed(false);
        FileNameExtensionFilter filter = new FileNameExtensionFilter("TXT", "txt");
        jfc.addChoosableFileFilter(filter);

        int returnValue = jfc.showOpenDialog(null);

        //Si el usuario agrega un txt.
        if (returnValue == JFileChooser.APPROVE_OPTION) {
            String auxpath = jfc.getSelectedFile().getPath();

            //Empezamos a leer el archivo cargado
            StringBuilder sb = new StringBuilder();
            String txt = "";

            try ( BufferedReader br = Files.newBufferedReader(Paths.get(auxpath))) {

                //Lectura linea por linea
                String line;

                while ((line = br.readLine()) != null) {

                    if (!line.isEmpty()) {
                        txt += line + "\n";
                    }

                }

                lecturaArchivo(txt, articulo, listaArticulos, hashTitulo, hashAutores, hashPalabras);
            } catch (IOException e) {
                System.err.format("IOException: %s%n", e);
            }

        }

    }//GEN-LAST:event_BotonAgregarActionPerformed

    private void ArticulosPorTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ArticulosPorTituloActionPerformed

        String titulosconcatenados = "";
        String concatenadobien = "";

        //TODO a
        if (!listaArticulos.esVacio()) {

            Nodo aux = listaArticulos.getpFirst();

            for (int k = 0; k < listaArticulos.Size(); k++) {

                Articulo aux1 = (Articulo) aux.getInfo();
                titulosconcatenados += aux1.getTitulo() + "//";

                aux = aux.getpNext();

            }
            concatenadobien = titulosconcatenados.substring(0, titulosconcatenados.length() - 2);

            String[] concatenadobiensplit = concatenadobien.split("//");

            JFrame jFrame = new JFrame("Articulos por titulo");
            JComboBox<String> jComboBox = new JComboBox<>(concatenadobiensplit);
            jComboBox.setBounds(20, 50, 400, 40);

            JButton jButton = new JButton("Escoger");
            jButton.setBounds(170, 100, 90, 20);

            JLabel jLabel = new JLabel();
            jLabel.setBounds(10, 100, 400, 100);

            jFrame.add(jButton);
            jFrame.add(jComboBox);
            jFrame.add(jLabel);

            jFrame.setLayout(null);
            jFrame.setSize(450, 200);
            jFrame.setVisible(true);
            jFrame.setLocationRelativeTo(null);

            jButton.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    String tituloseleccionado = "Haz escogido " + jComboBox.getItemAt(jComboBox.getSelectedIndex());
                    jLabel.setText(tituloseleccionado);
                    String titulobueno = jComboBox.getItemAt(jComboBox.getSelectedIndex());
                    int key = hashTitulo.stringtoNum(titulobueno);
                    int index = hashTitulo.getBucketIndex(key);
                    Articulo aux = (Articulo) hashTitulo.getBucketArray()[index].getValue();
                    aux.mostrarInfoTuneado(aux);
                }
            });

        } else {
            JOptionPane.showMessageDialog(null, "Error. No existen elementos en la base de datos.");
        }

    }//GEN-LAST:event_ArticulosPorTituloActionPerformed

    private void BotonBPAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonBPAutorActionPerformed
        if (!listaArticulos.esVacio()) {
            String concatenadoaux = "";

            Nodo aux2 = listaArticulos.getpFirst();

            while (aux2 != null) {

                Articulo aux3 = (Articulo) aux2.getInfo();
                Nodo aux4 = aux3.getAutores().getpFirst();

                //Adentro de lista autores para cada nodo
                for (int c = 0; c < aux3.getAutores().Size(); c++) {
                    concatenadoaux += aux4.getInfo().toString() + "//";

//                hashAutores.put_listas(aux4, aux2.getInfo());
                    aux4 = aux4.getpNext();
                }
                aux2 = aux2.getpNext();
            }

            String concatenadobien = concatenadoaux.substring(0, concatenadoaux.length() - 2);
            String[] concatenadoauxsplit = concatenadobien.split("//");
            int n = concatenadoauxsplit.length;
            String[] temp = Metodos.eliminarIguales(concatenadoauxsplit, n);

            JFrame jFrame = new JFrame("Articulos por Autores");
            JComboBox<String> jComboBox = new JComboBox<>(concatenadoauxsplit);
            jComboBox.setBounds(20, 50, 400, 40);

            JButton jButton = new JButton("Escoger");
            jButton.setBounds(170, 100, 90, 20);

            JLabel jLabel = new JLabel();
            jLabel.setBounds(10, 100, 400, 100);

            jFrame.add(jButton);
            jFrame.add(jComboBox);
            jFrame.add(jLabel);

            jFrame.setLayout(null);
            jFrame.setSize(450, 200);
            jFrame.setVisible(true);
            jFrame.setLocationRelativeTo(null);

            jButton.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    String autorseleccionado = "Haz escogido " + jComboBox.getItemAt(jComboBox.getSelectedIndex());
                    jLabel.setText(autorseleccionado);
                    String autorbueno = jComboBox.getItemAt(jComboBox.getSelectedIndex());
                    int key = hashAutores.stringtoNum(autorbueno);
                    int index = hashAutores.getBucketIndex(key);
                    Articulo aux = (Articulo) hashAutores.getBucketArray()[index].getValue();
                    aux.mostrarInfo();
                }
            });
        } else {
            JOptionPane.showMessageDialog(null, "Error. No existen elementos en la base de datos.");
        }

    }//GEN-LAST:event_BotonBPAutorActionPerformed

    private void BotonBPPCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonBPPCActionPerformed
        if (!listaArticulos.esVacio()) {
            String concatenadoaux = "";
            Nodo aux2 = listaArticulos.getpFirst();

            while (aux2 != null) {

                Articulo aux3 = (Articulo) aux2.getInfo();
                Nodo aux4 = aux3.getPalabrasClave().getpFirst();

                //Adentro de lista autores para cada nodo
                for (int c = 0; c < aux3.getPalabrasClave().Size(); c++) {
                    concatenadoaux += aux4.getInfo().toString() + "//";
                    aux4 = aux4.getpNext();
                }
                aux2 = aux2.getpNext();
            }

            String concatenadobien = concatenadoaux.substring(0, concatenadoaux.length() - 2);
            String[] concatenadoauxsplit = concatenadobien.split("//");
            int n = concatenadoauxsplit.length;
            String[] temp = Metodos.eliminarIguales(concatenadoauxsplit, n);

            JFrame jFrame = new JFrame("Articulos por Palabras Clave");
            JComboBox<String> jComboBox = new JComboBox<>(concatenadoauxsplit);
            jComboBox.setBounds(20, 50, 400, 40);

            JButton jButton = new JButton("Escoger");
            jButton.setBounds(170, 100, 90, 20);

            JLabel jLabel = new JLabel();
            jLabel.setBounds(10, 100, 400, 100);

            jFrame.add(jButton);
            jFrame.add(jComboBox);
            jFrame.add(jLabel);

            jFrame.setLayout(null);
            jFrame.setSize(450, 200);
            jFrame.setVisible(true);
            jFrame.setLocationRelativeTo(null);

            jButton.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    String autorseleccionado = "Haz escogido " + jComboBox.getItemAt(jComboBox.getSelectedIndex());
                    jLabel.setText(autorseleccionado);
                    String autorbueno = jComboBox.getItemAt(jComboBox.getSelectedIndex());
                    int key = hashPalabras.stringtoNum(autorbueno);
                    int index = hashPalabras.getBucketIndex(key);
                    Articulo aux = (Articulo) hashPalabras.getBucketArray()[index].getValue();
                    aux.mostrarInfo();
                }
            });
            System.out.println(jLabel.getText());
        } else {
            JOptionPane.showMessageDialog(null, "Error. No existen elementos en la base de datos.");
        }

    }//GEN-LAST:event_BotonBPPCActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ArticulosPorTitulo;
    private javax.swing.JButton BotonAgregar;
    private javax.swing.JButton BotonBPAutor;
    private javax.swing.JButton BotonBPPC;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
